# Generated by Django 4.0 on 2023-04-22 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baselinecheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_info',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='扫描时间'),
            preserve_default=False,
        ),
    ]
